### ISSUE TITLE
introduce parameter in compose.decompose-xmls.yaml to select numeric/alphanumeric pat-IDS

### ISSUE THREAD

**Issue by jasminziegler** [bzkf/onco-analytics-on-fhir#188]
Issue reported by Timo Fuchs, Clara Fischer, UK Regensburg:
- Issue: unwanted patIDs leading zeros in their XMLs, which are preserved within the pipeline, but they need them removed because these leading zeros do not appear in their actual patID and therefore the FHIR-Server can not match IDS and interprets the IDs with leading zeros as text
- proposed solution: patient_id = str(int(patient_stammdaten.get("Patient_ID"))
- problem with proposed solution: some locations also have alphanumeric patIDs
- idea: introduce a parameter in compose file to switch between numeric and alphanumeric patid, add if/else statement in decompose-xml.py based on parameter
- to do beforehand: check if this can cause any issues for the other locations

**Comment by pcvolkmer** [comment]
How about removing leading zeros in PatIDs as a first step? Right after ADT/oBDS messages are published as a Kafka record?

```
Kafka-Connect --> (remove leading zeros) --> ... do other steps 
```

The only problems that can occur are if someone wants to compare PatIDs with messages in the primary data source.

**Comment by chgl** [comment]
Maybe we can do it using smts https://docs.confluent.io/platform/current/connect/transforms/overview.html

**Comment by chgl** [comment]
Or in SQL directly?

**Comment by pcvolkmer** [comment]
Manipulating XML in SQL could be tricky. There is [EXTRACTVALUE()](https://mariadb.com/kb/en/extractvalue/) for MySQL and MariaDB, but no known way (for me) to manipulate XML.

**Comment by pcvolkmer** [comment]
Usable docker image is available here: https://github.com/pcvolkmer/rwdp-obds-cleanup/pkgs/container/rwdp-obds-cleanup

Just use it with own settings in example [docker-compose.yml](https://github.com/pcvolkmer/rwdp-obds-cleanup/blob/master/docker-compose/docker-compose.yml).

**Comment by pcvolkmer** [comment]
> Or in SQL directly?

I just found [UPDATEXML()](https://mariadb.com/kb/en/updatexml/) so it is possible to manipulate XML within SQL.

The following query can be used to achieve the desired result:

```
SELECT * FROM (
    SELECT
        YEAR(STR_TO_DATE(EXTRACTVALUE(lme.xml_daten, '//Diagnosedatum'), '%d.%c.%Y')) AS YEAR,
        versionsnummer AS VERSIONSNUMMER,
        lme.id AS ID,
        CASE
        # Patient_ID can be casted into number
            WHEN CAST(EXTRACTVALUE(lme.xml_daten, '//Patienten_Stammdaten/@Patient_ID') AS INT) > 0
            THEN CONVERT(
                UPDATEXML(
                    lme.xml_daten,
                    '//Patienten_Stammdaten/@Patient_ID',
                    CONCAT('Patient_ID="', EXTRACTVALUE(lme.xml_daten, '//Patienten_Stammdaten/@Patient_ID'),'"')
                ) USING utf8
            )
        ELSE
        # else fallback - do not touch Patient_ID
            CONVERT(lme.xml_daten USING UTF8)
        END AS XML_DATEN
    FROM lkr_meldung_export lme
    WHERE
        typ != '-1'
        AND versionsnummer IS NOT NULL
        AND lme.XML_DATEN LIKE '%ICD_Version%'
        AND EXTRACTVALUE(lme.xml_daten, '//ADT_GEKID/@Schema_Version') LIKE '2.%'
) o
```

Keep in mind that this query, if `Patient_ID` is not available or is alpanumeric, the query will return an unchanged XML.
